### PR TITLE
New Magic features: Magic barrier and Voice casting

### PR DESCRIPTION
**Pull request by Azer147**
**New Magic barrier spell effect:**
- Add +5 defense against incoming spell
- If saved against incoming spell the barrier will send the spell back to the sender !
- If not saved, the Player will still suffer from the incoming spell
- The magic barrier is one time use only, whether the player has saved against the spell or not, the magic barrier will disapear after.

**New Disarm spell effect:**
- remove the hand held item fo the target

**New Voice casting ability:**
- Ability to cast spell by sending normal message in chat: `<SpellName> <TargetName>`
- Limited to only one target
- Wand not requiered

If any change are required, let me know!
Azer #172401

### CODE REVIEW

**Comment by littlesera** [comment]
Great ideas! Thanks for the work! I wonder if it'd be neat to allow configuring a "magic word/phrase" for the spell so it can be different than the spell name?

**Comment by Azer147** [comment]
You welcome! thanks to your work that allow me to implement my ideas ^^

I'm not sure that adding another word/phrase for spell are necessary since the spell name is already quite permissive (can have space with long name already). I usually just edit the spell name for a cool name. But it's ultimatly your call to make^^.

Also i'm wondering if i should make the voice casting ability to require a wand, because it might be too powerfull right now.

**Comment by littlesera** [comment]
Maybe an override field so users can have a descriptive name and a "mystical" casting phrase?
I like the idea of requiring a wand/foci for voice casting, just so there's _some_ indication that spells might happen... though on the other hand being bound but casting voice spells until gagged is enticing :3
Likely would want to add a boolean to allow voice casting on a spell like potion, so not all of them could fire off if you mention them.

**Comment by Azer147** [comment]
Okay sure, i'll add the checkbox and the magic phrase soon !
Thanks for your reply !

**Comment by Azer147** [comment]
Well i added the Casting phrase option in the spell menu, but it seem that there was no space left, so now the "Allow potion" checkbox disapeared, and i just cannot figure out how to fix this. It's the first time i touch at the UI so i'm having trouble to get my head around it.
Do you have any idea ?

Also instead of having the Casting phrase and the checkbox to allow voice casting, now the Casting phrase is the only way to use voice casting, so it's already acting like an "Allow voice casting" option.

**Pull request merged**
