### PR TITLE
Refactor module load and settings registration

### PR DESCRIPTION
**Pull request by zorgjbe**
This removes the hardcoded settings arrays in favor of each module registering its own screen (name, icon and title), and refactors the code so screen discovery and unloading is more streamlined (I needed the latter for `Unload()` to work correctly, but then ended up not needing it 🤷).

Then the registration of default settings is moved over to modules themselves instead of subscreens, removing all the duplication, and make the screens go through their respective module when accessing settings. Most of the getters are now just a passthrough from a screen to the abstract class, to its module, to the abstract class.

This fixes a crash where opening the General settings would crash, as it would only initialize its values but tried to access stuff in the Misc module.

### CODE REVIEW

**Comment by zorgjbe** [comment]
Fixes #8

**Comment by littlesera** [comment]
I've been meaning to do something like this for a while, thanks for taking the initiative and sorry to leave a crashing bug so long!

**Comment by zorgjbe** [comment]
You're welcome! Though you might want to have a quick look, I think I broke the back menu in some cases? At least I remember ending up looking at a blank settings screen at one point.

**Comment by zorgjbe** [comment]
Another thing you might want to test is that I got the whole register settings right. Since I've never used the extension before, my own settings were pretty "default". I've tested that changing things and reloading kept settings, but the bare minimum, so if you have stuff with nested objects, it might be work making sure they don't get accidentally "defaulted".

**Pull request merged**
